// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealWorld.Api.Data;

#nullable disable

namespace RealWorld.Api.Migrations
{
    [DbContext(typeof(RealWorldDataContext))]
    [Migration("20221028165258_recreateDatabase")]
    partial class recreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ARTICLES_TAGS", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("INT");

                    b.Property<string>("TagName")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("ArticleId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("ARTICLES_TAGS");
                });

            modelBuilder.Entity("FAVORITES", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("INT");

                    b.Property<int>("FavoritedBy")
                        .HasColumnType("INT");

                    b.HasKey("ArticleId", "FavoritedBy");

                    b.HasIndex("FavoritedBy");

                    b.ToTable("FAVORITES");
                });

            modelBuilder.Entity("FOLLOWERS", b =>
                {
                    b.Property<int>("Follow")
                        .HasColumnType("INT");

                    b.Property<int>("FollowedBy")
                        .HasColumnType("INT");

                    b.HasKey("Follow", "FollowedBy");

                    b.HasIndex("FollowedBy");

                    b.ToTable("FOLLOWERS");
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ARTICLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 8,
                            Body = "Iste quia natus et dignissimos reiciendis ad nostrum totam. Totam voluptatibus doloremque eos asperiores cum ipsam illum. Doloribus aperiam cumque non recusandae est unde vitae amet. Exercitationem doloribus facilis omnis doloremque vel. A quas porro sed ad. Autem suscipit blanditiis ratione modi velit porro dolorum corrupti adipisci.\n\nId vero soluta fuga eius saepe eveniet dicta quo. Facilis dolorem eius repellat. Et quisquam consequatur aut qui porro. Et consectetur voluptatum ut. Tempore totam fugiat consequatur autem. Itaque exercitationem cupiditate nam sit quis qui modi amet.\n\nEligendi et molestiae modi non et ut. Explicabo voluptatem odit est tenetur quos ratione cum. Tempora et consequatur ea pariatur veritatis veniam.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 24, 11, 5, 12, 413, DateTimeKind.Unspecified).AddTicks(8675), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Doloribus iure cupiditate minima molestias provident inventore minima dolores nulla.",
                            Slug = "aut-quod-ea-recusandae-magni-cumque-et",
                            Title = "Aut quod ea recusandae magni cumque et.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 24, 11, 5, 12, 413, DateTimeKind.Unspecified).AddTicks(8675), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 9,
                            Body = "Quia sit est magnam repellat similique veritatis. Voluptas similique facilis sint ut. Excepturi sequi vel. In omnis tempore asperiores corporis et laudantium atque. Quasi incidunt voluptatem ducimus.\n\nIure illum sed. Doloremque molestias sapiente asperiores sit et minima delectus officia est. Quam aut rerum aut aliquam. Eveniet dolor aut perspiciatis.\n\nAliquid doloribus aperiam eligendi quia adipisci dolores. Voluptatem enim et repellendus dolores laborum natus. Laboriosam voluptatem aspernatur debitis quo saepe et aliquam. Voluptatum adipisci necessitatibus quos quidem. Consequatur et asperiores laborum alias. Sapiente nesciunt est sunt consectetur veritatis aut minus aut voluptas.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 3, 15, 38, 55, 286, DateTimeKind.Unspecified).AddTicks(9773), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Et quo eos ducimus et et praesentium.",
                            Slug = "omnis-molestiae-est-repellat-est",
                            Title = "Omnis molestiae est repellat est.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 3, 15, 38, 55, 286, DateTimeKind.Unspecified).AddTicks(9773), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "Officiis ut eos alias iste tempore vel et quia repellendus. Eum ut cupiditate neque harum omnis ipsam. Et praesentium et laboriosam. Voluptatem distinctio quia sed. Est atque aut odio sed eos error.\n\nPerferendis similique praesentium asperiores quia quia veniam harum. Aliquam voluptatem perferendis dignissimos exercitationem voluptas qui provident hic. Rerum at eveniet totam. Ex omnis corporis quam reprehenderit nihil nam animi recusandae. Ullam soluta nisi totam et eius voluptates occaecati eos hic.\n\nVoluptas amet voluptatem et officia voluptates. Possimus temporibus sed aut laborum. Sunt illum et labore autem deserunt nam vitae. Asperiores nesciunt deleniti veritatis voluptatem maiores eaque.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 4, 21, 21, 58, 9, 221, DateTimeKind.Unspecified).AddTicks(3445), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Sint sunt vero.",
                            Slug = "fugit-nesciunt-omnis-fugiat",
                            Title = "Fugit nesciunt omnis fugiat.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 4, 21, 21, 58, 9, 221, DateTimeKind.Unspecified).AddTicks(3445), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 8,
                            Body = "Quia dolor in qui. Tempora in quae minima atque ex est esse autem. Aut dolores cupiditate possimus.\n\nBlanditiis dicta qui ipsa omnis ut cumque impedit. Perspiciatis quo nihil et voluptate illum. Facere ut et qui doloribus ab unde. Delectus dignissimos et et.\n\nNemo repellat et blanditiis libero explicabo asperiores est. Aut cumque laboriosam. Earum occaecati sit excepturi eum autem occaecati eum nostrum.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 5, 22, 32, 45, 271, DateTimeKind.Unspecified).AddTicks(384), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Qui ea sed nihil architecto suscipit sint omnis et.",
                            Slug = "ut-quo-iste-qui-quod-quisquam-officia-veritatis-sit",
                            Title = "Ut quo iste qui quod quisquam officia veritatis sit.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 10, 5, 22, 32, 45, 271, DateTimeKind.Unspecified).AddTicks(384), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Body = "Ut est rerum dolor recusandae quae perspiciatis sed. Sit dolorem architecto est voluptatem. Similique et porro delectus molestiae nobis asperiores. Soluta fuga inventore rerum expedita recusandae voluptatem odit. Et architecto dolorem molestiae repellendus nostrum ea accusamus incidunt. Similique eius tempore.\n\nDeleniti neque voluptatem ducimus totam architecto a ut. Et sapiente sequi officiis. Necessitatibus animi itaque voluptates autem dolorem. Explicabo harum repellendus quia ipsam explicabo eligendi similique.\n\nAut qui suscipit neque quos voluptates. Rerum porro rerum odit molestiae sit qui eos non. Laboriosam sint et enim exercitationem ipsam. Iure provident ut.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 0, 50, 23, 186, DateTimeKind.Unspecified).AddTicks(6612), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Reiciendis ut in illum.",
                            Slug = "tenetur-aut-ut-et-qui-est",
                            Title = "Tenetur aut ut et qui est.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 0, 50, 23, 186, DateTimeKind.Unspecified).AddTicks(6612), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "Modi unde dolorem laborum sapiente amet repellendus et. Ab quibusdam ipsum quo eum. Est sapiente tempore placeat quos. Soluta nihil odit mollitia accusamus consequuntur doloribus tempora.\n\nSimilique ipsa quidem explicabo non eius sint ad earum. Aliquid repudiandae aliquid voluptatem magnam. Sit minima totam et. Ipsam omnis et. Voluptas veritatis perferendis sunt inventore quibusdam ea. Tempora incidunt magni architecto id minus.\n\nIn aut consequuntur. Assumenda ex dicta ut et earum. Possimus excepturi consequatur magnam ut quo omnis nobis. Ut sit aut error. Quas quia autem quia dolorem ducimus perspiciatis repudiandae iure et.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 20, 12, 35, 16, 495, DateTimeKind.Unspecified).AddTicks(6423), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Ut assumenda corrupti aut libero laudantium sed sunt.",
                            Slug = "eveniet-esse-reiciendis-eos-commodi-sit-ab-qui",
                            Title = "Eveniet esse reiciendis eos commodi sit ab qui.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 20, 12, 35, 16, 495, DateTimeKind.Unspecified).AddTicks(6423), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "Natus iusto ut incidunt exercitationem tempora laudantium dolores neque voluptas. Consectetur quod et. Repellendus adipisci sit ut.\n\nVoluptatum corporis id impedit vel quaerat et ut dolores. Dolore in officia dicta aut quas quaerat. Dignissimos alias dolorum molestiae aut omnis modi labore. Consectetur qui at numquam. Dolores nesciunt dicta dolores nam occaecati deleniti delectus distinctio incidunt.\n\nDebitis autem sequi provident quasi. Itaque et autem porro qui. Dolores dolorem atque sunt sit laborum accusamus. Corporis laboriosam ut molestiae alias ut quo id. Voluptatum laboriosam reprehenderit quaerat.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 1, 47, 21, 791, DateTimeKind.Unspecified).AddTicks(6164), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Et dicta quo sed fugit repudiandae quo fugit dolor perferendis.",
                            Slug = "quidem-quo-eaque-voluptates-hic-ab-ea",
                            Title = "Quidem quo eaque voluptates hic ab ea.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 1, 47, 21, 791, DateTimeKind.Unspecified).AddTicks(6164), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Body = "Necessitatibus est provident aut dignissimos velit ullam. Autem facere nostrum perferendis non. Atque corporis quos.\n\nDeserunt modi quia velit laudantium sit alias cumque. Non nostrum aperiam ut laudantium. Perspiciatis commodi sit sit tempore. Velit quibusdam ea voluptatem dolore fuga voluptates maiores. Facilis iste est exercitationem molestiae ipsam. Enim quasi assumenda dignissimos et aut temporibus vitae quisquam.\n\nSimilique molestias quia quia rem vitae perferendis. Molestiae porro voluptatem numquam. Sunt porro et aut id nihil earum aperiam.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 8, 36, 50, 883, DateTimeKind.Unspecified).AddTicks(7108), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Ab fugit magnam tempora numquam in consequatur voluptatem perspiciatis.",
                            Slug = "architecto-nisi-voluptatum-corporis",
                            Title = "Architecto nisi voluptatum corporis.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 8, 36, 50, 883, DateTimeKind.Unspecified).AddTicks(7108), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            Body = "Minima magnam necessitatibus quae neque at veritatis. Repellendus ratione voluptates ut exercitationem. Sint occaecati minus.\n\nModi at quibusdam. Quam in id sit quidem placeat et error ex. Eveniet distinctio repellendus nesciunt qui rerum quaerat consectetur.\n\nAliquam aspernatur aut magnam vitae iste. Quod incidunt sint eos cum deleniti rem totam est. Quo molestiae id perspiciatis qui iste optio. Ducimus minus commodi alias amet placeat. Reiciendis consequatur cupiditate. Molestiae ex recusandae beatae non.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 12, 41, 24, 317, DateTimeKind.Unspecified).AddTicks(3448), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Quo temporibus modi dolor enim.",
                            Slug = "vitae-voluptas-nihil-voluptas-ad-necessitatibus-tempore-ut",
                            Title = "Vitae voluptas nihil voluptas ad necessitatibus tempore ut.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 12, 41, 24, 317, DateTimeKind.Unspecified).AddTicks(3448), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            Body = "Dolorem blanditiis quod ipsa assumenda eum cumque fugit. Ratione modi quia ut ut tempore ipsa magnam porro et. Ut quam cum et. Voluptas ut nihil voluptatum pariatur dolor voluptatem et ullam. Voluptatum possimus nostrum quasi sapiente. Et commodi ut eos sed occaecati esse.\n\nQuam dolorem quis cum commodi voluptate dolor qui dolor. Natus repellat quidem aspernatur consequatur quasi. Animi explicabo velit quis a est rerum et. Illo dolores inventore maxime. At aut harum molestiae a dolor dolorem recusandae nulla.\n\nFugit et in cupiditate molestiae voluptatem ipsum temporibus esse sint. Ea natus laudantium quia nihil. Neque aliquid facilis. Iusto harum impedit saepe consequatur libero velit nostrum debitis. Dolore quas aliquid nulla sit perspiciatis consequuntur est.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 9, 22, 4, 3, 39, 257, DateTimeKind.Unspecified).AddTicks(5851), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Enim voluptas necessitatibus provident cumque quasi delectus dolor ex et.",
                            Slug = "dolores-ab-quia-soluta-repellat-eligendi-harum-nihil-deserunt",
                            Title = "Dolores ab quia soluta repellat eligendi harum nihil deserunt.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 9, 22, 4, 3, 39, 257, DateTimeKind.Unspecified).AddTicks(5851), new TimeSpan(0, -3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RealWorld.Api.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArticleId")
                        .HasColumnType("INT");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("COMMENTS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 8,
                            AuthorId = 9,
                            Body = "Iste quia natus et dignissimos reiciendis ad nostrum totam.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 23, 47, 52, 627, DateTimeKind.Unspecified).AddTicks(6022), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 23, 47, 52, 627, DateTimeKind.Unspecified).AddTicks(6022), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 5,
                            AuthorId = 10,
                            Body = "Eos asperiores cum.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 8, 23, 23, 917, DateTimeKind.Unspecified).AddTicks(5785), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 8, 23, 23, 917, DateTimeKind.Unspecified).AddTicks(5785), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 9,
                            AuthorId = 9,
                            Body = "Aperiam cumque non recusandae est unde vitae amet qui exercitationem.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 17, 12, 24, 54, 499, DateTimeKind.Unspecified).AddTicks(8606), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 17, 12, 24, 54, 499, DateTimeKind.Unspecified).AddTicks(8606), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 7,
                            AuthorId = 8,
                            Body = "Vel nisi a.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 13, 54, 44, 955, DateTimeKind.Unspecified).AddTicks(5979), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 13, 54, 44, 955, DateTimeKind.Unspecified).AddTicks(5979), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 8,
                            AuthorId = 2,
                            Body = "Et autem suscipit blanditiis ratione.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 13, 55, 32, 477, DateTimeKind.Unspecified).AddTicks(2070), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 1, 16, 13, 55, 32, 477, DateTimeKind.Unspecified).AddTicks(2070), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 5,
                            AuthorId = 8,
                            Body = "Corrupti adipisci debitis dolorem id vero soluta.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 15, 50, 11, 620, DateTimeKind.Unspecified).AddTicks(7865), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 15, 50, 11, 620, DateTimeKind.Unspecified).AddTicks(7865), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 3,
                            AuthorId = 9,
                            Body = "Dicta quo ipsum facilis dolorem eius repellat deleniti et quisquam.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 4, 22, 17, 23, 46, 788, DateTimeKind.Unspecified).AddTicks(2803), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 4, 22, 17, 23, 46, 788, DateTimeKind.Unspecified).AddTicks(2803), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 2,
                            AuthorId = 8,
                            Body = "Consequuntur et consectetur voluptatum ut voluptas tempore totam.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 11, 39, 9, 419, DateTimeKind.Unspecified).AddTicks(2751), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 11, 39, 9, 419, DateTimeKind.Unspecified).AddTicks(2751), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 9,
                            AuthorId = 8,
                            Body = "Itaque exercitationem cupiditate nam sit quis qui modi amet.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 14, 20, 4, 346, DateTimeKind.Unspecified).AddTicks(296), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 14, 20, 4, 346, DateTimeKind.Unspecified).AddTicks(296), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 7,
                            AuthorId = 7,
                            Body = "Molestiae modi non et ut cum explicabo voluptatem.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 4, 21, 24, 214, DateTimeKind.Unspecified).AddTicks(9554), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 4, 21, 24, 214, DateTimeKind.Unspecified).AddTicks(9554), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 7,
                            AuthorId = 10,
                            Body = "Ratione cum similique tempora et consequatur.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 10, 27, 6, 923, DateTimeKind.Unspecified).AddTicks(645), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 11, 10, 27, 6, 923, DateTimeKind.Unspecified).AddTicks(645), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 9,
                            AuthorId = 1,
                            Body = "Nihil a doloribus iure cupiditate.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 19, 25, 4, 425, DateTimeKind.Unspecified).AddTicks(2527), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 16, 19, 25, 4, 425, DateTimeKind.Unspecified).AddTicks(2527), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 6,
                            AuthorId = 6,
                            Body = "Minima dolores nulla.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 21, 3, 18, 13, 335, DateTimeKind.Unspecified).AddTicks(3345), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 21, 3, 18, 13, 335, DateTimeKind.Unspecified).AddTicks(3345), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 2,
                            AuthorId = 8,
                            Body = "Recusandae magni cumque et eum nobis.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 5, 19, 21, 37, DateTimeKind.Unspecified).AddTicks(3780), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 5, 19, 21, 37, DateTimeKind.Unspecified).AddTicks(3780), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            ArticleId = 2,
                            AuthorId = 2,
                            Body = "Magnam repellat similique veritatis voluptatem voluptas similique.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 7, 9, 8, 832, DateTimeKind.Unspecified).AddTicks(8696), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 4, 7, 9, 8, 832, DateTimeKind.Unspecified).AddTicks(8696), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            ArticleId = 6,
                            AuthorId = 10,
                            Body = "Excepturi sequi vel.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 21, 4, 0, 30, 336, DateTimeKind.Unspecified).AddTicks(3808), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 21, 4, 0, 30, 336, DateTimeKind.Unspecified).AddTicks(3808), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            ArticleId = 6,
                            AuthorId = 6,
                            Body = "Asperiores corporis et laudantium atque numquam quasi incidunt.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 6, 20, 16, 12, 28, 436, DateTimeKind.Unspecified).AddTicks(5496), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 6, 20, 16, 12, 28, 436, DateTimeKind.Unspecified).AddTicks(5496), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            ArticleId = 5,
                            AuthorId = 5,
                            Body = "Iure illum sed.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 22, 46, 0, 754, DateTimeKind.Unspecified).AddTicks(9959), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 22, 46, 0, 754, DateTimeKind.Unspecified).AddTicks(9959), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            ArticleId = 1,
                            AuthorId = 6,
                            Body = "Asperiores sit et minima delectus officia est quia quam aut.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 8, 25, 8, 21, 2, 777, DateTimeKind.Unspecified).AddTicks(9698), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 8, 25, 8, 21, 2, 777, DateTimeKind.Unspecified).AddTicks(9698), new TimeSpan(0, -3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            ArticleId = 10,
                            AuthorId = 3,
                            Body = "Eveniet dolor aut perspiciatis.",
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 9, 22, 22, 54, 7, 166, DateTimeKind.Unspecified).AddTicks(1177), new TimeSpan(0, -3, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2022, 9, 22, 22, 54, 7, 166, DateTimeKind.Unspecified).AddTicks(1177), new TimeSpan(0, -3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RealWorld.Api.Models.TagModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Name");

                    b.ToTable("TAGS", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "est"
                        },
                        new
                        {
                            Name = "illum"
                        },
                        new
                        {
                            Name = "assumenda"
                        },
                        new
                        {
                            Name = "iste"
                        },
                        new
                        {
                            Name = "quia"
                        },
                        new
                        {
                            Name = "natus"
                        },
                        new
                        {
                            Name = "et"
                        },
                        new
                        {
                            Name = "dignissimos"
                        },
                        new
                        {
                            Name = "reiciendis"
                        },
                        new
                        {
                            Name = "ad"
                        });
                });

            modelBuilder.Entity("RealWorld.Api.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Image")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Illum assumenda iste quia natus et dignissimos reiciendis.\nNostrum totam harum totam voluptatibus.\nEos asperiores cum.",
                            Email = "Reagan.Stanton69@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
                            PasswordHash = "10000.ZiJTadfBrqA1nuIToOMJLw==.gKRHw0IVosl1pweo/nfCCRP7sKnJnYHMC8UJtxMsOQg=",
                            Username = "Trace Pfeffer"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Vitae amet qui exercitationem doloribus facilis omnis.\nVel nisi a.\nPorro sed ad et autem suscipit blanditiis.",
                            Email = "Dallin_Jast48@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/243.jpg",
                            PasswordHash = "10000.8ahMOp9SfG+cnAuGEd3XNg==.Mdd5FuiDGtsu5kpJCklmQtM7zGnnQXGVGbcnx1pt328=",
                            Username = "Shad Shanahan"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Vero soluta fuga eius saepe eveniet dicta quo.\nFacilis dolorem eius repellat.\nEt quisquam consequatur aut qui porro.",
                            Email = "Susan_Dickens@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/406.jpg",
                            PasswordHash = "10000.65xW27T9h+dJEsxVZdS9pA==.MnL6NAaTvaOqvxQbmIFhGkTuBfg4TfmXeIQa0ywm07g=",
                            Username = "Marcos Koss"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Consequatur autem voluptas itaque exercitationem cupiditate nam sit quis.\nModi amet quasi fuga eligendi et molestiae modi non.\nUt cum explicabo.",
                            Email = "Benny.Monahan14@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
                            PasswordHash = "10000.f/YEls5ktXG0EjWDvK3jxg==.M968h1FFeyEZmbbUfKEw9r8pUHy6P5ZLmVT8vlGFnhQ=",
                            Username = "Kevin Fahey"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Consequatur ea pariatur veritatis veniam nihil a.\nIure cupiditate minima molestias provident inventore minima dolores nulla laborum.\nQuod ea recusandae.",
                            Email = "Maximo_Morissette56@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/215.jpg",
                            PasswordHash = "10000.osHP59R/cYQ5eJcFWTNUfA==.S6/iNboW8NYEm460Wec6Kz98z+gxWk9eAIg0VAUcAWE=",
                            Username = "Christina Monahan"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Repellat similique veritatis voluptatem voluptas.\nFacilis sint ut beatae excepturi sequi vel.\nIn omnis tempore asperiores corporis et laudantium atque.",
                            Email = "Antonia44@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/563.jpg",
                            PasswordHash = "10000.7/Xc6w4B6zjOoU9EZip2Yw==.iC7vAacS433tqEt4bVde8Qp32gI5WRceSzQtZXnwlBo=",
                            Username = "Aisha Howell"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Sed repudiandae doloremque molestias sapiente asperiores sit et minima.\nOfficia est quia quam aut rerum aut aliquam magni eveniet.\nAut perspiciatis repellendus excepturi.",
                            Email = "Zachariah.Bartoletti19@yahoo.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/620.jpg",
                            PasswordHash = "10000.9F0iTrfa/JgFTbZaSWNVWQ==.tnkZ2BMc1WnalmGEXkk0CTveouI/ks8+5UYHA2yzzXc=",
                            Username = "Krista Gibson"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Et repellendus dolores laborum natus.\nLaboriosam voluptatem aspernatur debitis quo saepe et aliquam.\nVoluptatum adipisci necessitatibus quos quidem.",
                            Email = "Frida_Frami0@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1229.jpg",
                            PasswordHash = "10000.ja0uiOXPHQLNrpnLelstBw==.vn4P2l8sfapAjKkH7oUuzu91ehplf77jF5FFUVmdxm4=",
                            Username = "Vidal Crona"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Sunt consectetur veritatis aut minus aut voluptas facilis sunt.\nQuo eos ducimus et.\nPraesentium laboriosam omnis molestiae est repellat est sunt fuga.",
                            Email = "Scarlett0@hotmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/696.jpg",
                            PasswordHash = "10000.jShZFh6ZyCYapxC1Ki9vbQ==.xRWJyUldz9Dcmhvh1KmvUOEcUw32S8pux9yQqi0PS60=",
                            Username = "Margarett Hoeger"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Quia repellendus occaecati eum ut cupiditate neque harum omnis.\nMagnam et praesentium et laboriosam.\nVoluptatem distinctio quia sed.",
                            Email = "Oma43@yahoo.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/149.jpg",
                            PasswordHash = "10000.vL+1WT5biI7rJy6/YihhOQ==.lF2oiVbPiFF40/niKXAbI2IbtKUak0bwOu39k1K1aXg=",
                            Username = "Rylee Maggio"
                        });
                });

            modelBuilder.Entity("ARTICLES_TAGS", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAVORITES", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("FavoritedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FOLLOWERS", b =>
                {
                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("Follow")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("FollowedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.HasOne("RealWorld.Api.Models.UserModel", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RealWorld.Api.Models.CommentModel", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("RealWorld.Api.Models.UserModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
