// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealWorld.Api.Data;

#nullable disable

namespace RealWorldApi.Migrations
{
    [DbContext(typeof(RealWorldDataContext))]
    [Migration("20221027212531_addUserSeed")]
    partial class addUserSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ARTICLES_TAGS", b =>
                {
                    b.Property<string>("ArticleSlug")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TagName")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("ArticleSlug", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("ARTICLES_TAGS");
                });

            modelBuilder.Entity("FAVORITES", b =>
                {
                    b.Property<string>("ArticleSlug")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("FavoritedBy")
                        .HasColumnType("INT");

                    b.HasKey("ArticleSlug", "FavoritedBy");

                    b.HasIndex("FavoritedBy");

                    b.ToTable("FAVORITES");
                });

            modelBuilder.Entity("FOLLOWERS", b =>
                {
                    b.Property<int>("Follow")
                        .HasColumnType("INT");

                    b.Property<int>("FollowedBy")
                        .HasColumnType("INT");

                    b.HasKey("Follow", "FollowedBy");

                    b.HasIndex("FollowedBy");

                    b.ToTable("FOLLOWERS");
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.HasKey("Slug");

                    b.HasIndex("AuthorId");

                    b.ToTable("ARTICLE", (string)null);
                });

            modelBuilder.Entity("RealWorld.Api.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArticleSlug")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET");

                    b.HasKey("Id");

                    b.HasIndex("ArticleSlug");

                    b.HasIndex("AuthorId");

                    b.ToTable("COMMENTS", (string)null);
                });

            modelBuilder.Entity("RealWorld.Api.Models.TagModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Name");

                    b.ToTable("TAGS", (string)null);
                });

            modelBuilder.Entity("RealWorld.Api.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Image")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Illum assumenda iste quia natus et dignissimos reiciendis.\nNostrum totam harum totam voluptatibus.\nEos asperiores cum.",
                            Email = "Reagan.Stanton69@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
                            PasswordHash = "10000.CDwzHa+tbw8gAtkbIpGcvg==.KtEe4VNzAOezWwvgMHiu/kFcRwNtfR1xnXL00fv/oW8=",
                            Username = "Trace Pfeffer"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Vitae amet qui exercitationem doloribus facilis omnis.\nVel nisi a.\nPorro sed ad et autem suscipit blanditiis.",
                            Email = "Dallin_Jast48@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/243.jpg",
                            PasswordHash = "10000.3JMyX0U84yjgJY+kpvcdfA==.14JjjNRCg1S/jrTsBkPWRdgKBl9sKHWJyKgrlLR3cQM=",
                            Username = "Shad Shanahan"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Vero soluta fuga eius saepe eveniet dicta quo.\nFacilis dolorem eius repellat.\nEt quisquam consequatur aut qui porro.",
                            Email = "Susan_Dickens@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/406.jpg",
                            PasswordHash = "10000.GkBqVUYXAl9qXCFfcKkBpw==.Cz6FhYBLkPgznnm5hcizM7J5MU68761znrALa2nA0Xs=",
                            Username = "Marcos Koss"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Consequatur autem voluptas itaque exercitationem cupiditate nam sit quis.\nModi amet quasi fuga eligendi et molestiae modi non.\nUt cum explicabo.",
                            Email = "Benny.Monahan14@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
                            PasswordHash = "10000.P2a1ukFp/ihf+75ty2rLjg==.J8iD9XoJmpxNrNZTSFMDohvHvZqvEloALkKO1Eg9EcE=",
                            Username = "Kevin Fahey"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Consequatur ea pariatur veritatis veniam nihil a.\nIure cupiditate minima molestias provident inventore minima dolores nulla laborum.\nQuod ea recusandae.",
                            Email = "Maximo_Morissette56@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/215.jpg",
                            PasswordHash = "10000.iSp78b8YJg90dWTJTmTZXA==.3wPJkNM2GYWxdeTihfPDgxelucQv/fUW+ymroyVLcXc=",
                            Username = "Christina Monahan"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Repellat similique veritatis voluptatem voluptas.\nFacilis sint ut beatae excepturi sequi vel.\nIn omnis tempore asperiores corporis et laudantium atque.",
                            Email = "Antonia44@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/563.jpg",
                            PasswordHash = "10000.ZCcy/lH4JbGZxGafcQUx/A==.MZL8rvOXNoh8RnhykaLw6VjJH672x5W6S9SJoXPm1TI=",
                            Username = "Aisha Howell"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Sed repudiandae doloremque molestias sapiente asperiores sit et minima.\nOfficia est quia quam aut rerum aut aliquam magni eveniet.\nAut perspiciatis repellendus excepturi.",
                            Email = "Zachariah.Bartoletti19@yahoo.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/620.jpg",
                            PasswordHash = "10000.Mgjfyk85G1N4Od9cYFUgTQ==.ohdvNDaSKdV/dkzxx8BLhJm75nVKD01910SDLRZo/8Q=",
                            Username = "Krista Gibson"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Et repellendus dolores laborum natus.\nLaboriosam voluptatem aspernatur debitis quo saepe et aliquam.\nVoluptatum adipisci necessitatibus quos quidem.",
                            Email = "Frida_Frami0@gmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1229.jpg",
                            PasswordHash = "10000.48vC0b6cK9AGdubRooIvEQ==.N3xqewHehJzXH2iZsa8MCCvrGa6SQUqCKrEdt55RkvQ=",
                            Username = "Vidal Crona"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Sunt consectetur veritatis aut minus aut voluptas facilis sunt.\nQuo eos ducimus et.\nPraesentium laboriosam omnis molestiae est repellat est sunt fuga.",
                            Email = "Scarlett0@hotmail.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/696.jpg",
                            PasswordHash = "10000.xzxHoIuS2BgtuSiMQCrPQw==.rmq5OnO5iH6x8T+dlUG29rZDPBHXVPmGiqzGlMYdWY0=",
                            Username = "Margarett Hoeger"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Quia repellendus occaecati eum ut cupiditate neque harum omnis.\nMagnam et praesentium et laboriosam.\nVoluptatem distinctio quia sed.",
                            Email = "Oma43@yahoo.com",
                            Image = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/149.jpg",
                            PasswordHash = "10000.EMMMrJMxbQafGGNzEt2DpA==.ahUqel9uWPG8SkofViTf6ch4XxujML956fjN3Bn6DB4=",
                            Username = "Rylee Maggio"
                        });
                });

            modelBuilder.Entity("ARTICLES_TAGS", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", null)
                        .WithMany()
                        .HasForeignKey("ArticleSlug")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FAVORITES", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", null)
                        .WithMany()
                        .HasForeignKey("ArticleSlug")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("FavoritedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FOLLOWERS", b =>
                {
                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("Follow")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("FollowedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.HasOne("RealWorld.Api.Models.UserModel", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RealWorld.Api.Models.CommentModel", b =>
                {
                    b.HasOne("RealWorld.Api.Models.ArticleModel", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleSlug")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealWorld.Api.Models.UserModel", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RealWorld.Api.Models.ArticleModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("RealWorld.Api.Models.UserModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
